apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    env: production
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: 50Mi
          cpu: "0.2"
        requests:
          memory: 10Mi
          cpu: "0.1"