# Run with kubectl create -f pod-definition.yml
# Delete with kubectl delete -f pod-definition.yml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: 50Mi
          cpu: "0.2"
        requests:
          memory: 10Mi
          cpu: "0.1"