apiVersion: v1
kind: Pod
metadata:
  name: result
  labels:
    app: result
spec:
  containers:
  - name: result
    image: dockersamples/examplevotingapp_result
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
      requests:
        memory: 64Mi
        cpu: 100m
    ports:
      - containerPort: 80
        name: result
