apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: 50Mi
          cpu: "0.2"
        requests:
          memory: 10Mi
          cpu: "0.1"

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - port: 81
      targetPort: 80
      # nodePort: 30008
  selector:
    app: myapp
status:
  loadBalancer: {}