apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    tier: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp-pod
        tier: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            limits:
              memory: 50Mi
              cpu: "0.2"
            requests:
              memory: 10Mi
              cpu: "0.1"